title: Vibe Coding Playbook
description: "Vibe Coding Let's do it right! - ACS Branch Forum Sep 2025"
author: Sam Fernando
baseurl: "/VibeCodingPlaybook"
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  slides:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "slides"
    values:
      layout: "slide"
